# Generated by Django 5.2.1 on 2025-05-15 23:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Indicadores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicador',
            name='data_registro',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
